language: ruby
rvm:
  - "2.0.0"
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - rake db:migrate RAILS_ENV=test
  - bundle exec rake db:test:prepare 
  - bundle exec rspec -c spec
